CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.FILEFORMAT_STAGE
    url = 's3://snowflake-assignments-mc/fileformat/';


CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.EXERCISE_FILEFORMAT
    FIELD_DELIMITER = '|',
    SKIP_HEADER = 1;

DESC FILE FORMAT MANAGE_DB.FILE_FORMATS.EXERCISE_FILEFORMAT;

LIST @MANAGE_DB.EXTERNAL_STAGES.FILEFORMAT_STAGE;

TRUNCATE TABLE EXERCISE_DB.PUBLIC.CUSTOMERS;

COPY INTO EXERCISE_DB.PUBLIC.CUSTOMERS
    FROM @MANAGE_DB.EXTERNAL_STAGES.FILEFORMAT_STAGE
    FILE_FORMAT = (FORMAT_NAME=MANAGE_DB.FILE_FORMATS.EXERCISE_FILEFORMAT);
    
    

    
    FROM @MANAGE_DB.external_stages.aws_stage_errorex
    file_format= (FORMAT_NAME=MANAGE_DB.file_formats.my_file_format)
    files = ('OrderDetails_error.csv')
    ON_ERROR = 'SKIP_FILE_3'; 