SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER_ADDRESS
SAMPLE ROW (1) SEED (2);

CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.CUSTOMER_ADDRESS_SAMPLE_5 AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER_ADDRESS
SAMPLE ROW (1) SEED (2);

SELECT * FROM EXERCISE_DB.PUBLIC.CUSTOMER_ADDRESS_SAMPLE_5;

SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER
SAMPLE SYSTEM (1) SEED (2);

CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.CUSTOMER_SAMPLE_1 AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER
SAMPLE SYSTEM (1) SEED (2);

SELECT * FROM EXERCISE_DB.PUBLIC.CUSTOMER_SAMPLE_1;



