SELECT * FROM EXERCISE_DB.PUBLIC.JSON_RAW;
SELECT 
    RAW:first_name,
    RAW:last_name,
    RAW:Skills[0],
    RAW:Skills[1]
FROM EXERCISE_DB.PUBLIC.JSON_RAW;

CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.JSON_EMPLOYEES_SKILLS (
    first_name  STRING,
    last_name   STRING,
    skill1      STRING,
    skill2      STRING
);


INSERT INTO EXERCISE_DB.PUBLIC.JSON_EMPLOYEES_SKILLS 
(SELECT 
    RAW:first_name::STRING,
    RAW:last_name::STRING,
    RAW:Skills[0]::STRING,
    RAW:Skills[1]::STRING
FROM EXERCISE_DB.PUBLIC.JSON_RAW);

SELECT * FROM EXERCISE_DB.PUBLIC.JSON_EMPLOYEES_SKILLS
Where first_name = 'Florina';