-- Switch to role of accountadmin --
 
USE ROLE ACCOUNTADMIN;
USE DATABASE EXERCISE_DB;
USE WAREHOUSE COMPUTE_WH;
 
CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.PART
AS
SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."PART";
 
SELECT * FROM PART
ORDER BY P_MFGR DESC;


UPDATE EXERCISE_DB.PUBLIC.PART
SET P_MFGR='Manufacturer#CompanyX'
WHERE P_MFGR='Manufacturer#5';
 
----> Note down query id here:
 
SELECT * FROM PART
ORDER BY P_MFGR DESC;


SELECT * FROM PART at (OFFSET => -60*1.5) ORDER BY P_MFGR DESC;

SELECT * FROM PART before (statement => 'your-query-id');
