CREATE DATABASE TIMETRAVEL_EXERCISE;
CREATE SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;

CREATE TABLE CUSTOMER AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
LIMIT 500;

DROP SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;

SELECT * FROM COMPANY_X.CUSTOMER;

UNDROP SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;