USE DATABASE EXERCISE_DB;

CREATE OR REPLACE TABLE EMPLOYEES (
    CUSTOMER_ID INT,
    FIRST_NAME  VARCHAR(50),
    LAST_NAME   VARCHAR(50),
    EMAIL       VARCHAR(50),
    AGE         INT,
    DEPARTMENT  VARCHAR(50)

);

CREATE OR REPLACE STAGE AWS_COPYSTAGE
    url = 's3://snowflake-assignments-mc/copyoptions/example2/';

LIST @AWS_COPYSTAGE;

CREATE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV',
    FIELD_DELIMITER = ',',
    SKIP_HEADER = 1;

COPY INTO EMPLOYEES 
    FROM @AWS_COPYSTAGE
    FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
    VALIDATION_MODE = RETURN_ERRORS;

COPY INTO EMPLOYEES 
    FROM @AWS_COPYSTAGE
    FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
    TRUNCATECOLUMNS = TRUE;
    