 
USE ROLE ACCOUNTADMIN;
USE DATABASE EXERCISE_DB;
USE WAREHOUSE COMPUTE_WH;
 
CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.SUPPLIER
AS
SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."SUPPLIER";



CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.COPY_SUPPLIER
CLONE EXERCISE_DB.PUBLIC.SUPPLIER;

UPDATE EXERCISE_DB.PUBLIC.COPY_SUPPLIER
SET S_PHONE='###';

SELECT * FROM EXERCISE_DB.PUBLIC.COPY_SUPPLIER;

CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.COPY_COPY_SUPPLIER
CLONE EXERCISE_DB.PUBLIC.COPY_SUPPLIER before (statement => '01bf253e-0001-035f-0000-b3b1000a31de');

SELECT * FROM EXERCISE_DB.PUBLIC.COPY_COPY_SUPPLIER;

DROP TABLE EXERCISE_DB.PUBLIC.SUPPLIER;
DROP TABLE EXERCISE_DB.PUBLIC.COPY_SUPPLIER;
DROP TABLE EXERCISE_DB.PUBLIC.COPY_COPY_SUPPLIER;